[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.build]
cmds = [
  "npm install --prefix backend",
  "npm install --prefix frontend", 
  "npm run build --prefix frontend"
]

[phases.start]
cmd = "npm run start --prefix backend"

[variables]
NODE_ENV = "production"